preset: laravel

enabled:
  - strict
  - unalign_double_arrow
  - phpdoc_order
  - phpdoc_separation

disabled:
  - short_array_syntax
  - simplified_null_return

finder:
  exclude:
    - "public"
    - "resources"
    - "tests"
  name:
    - "*.php"
